### ISSUE TITLE
Removing excluded genres causes an error

### ISSUE THREAD

**Issue by zybron** [Shadow229/Server-API-Calls#4]
After removing all excluded movie genres from the array in options.py I get the following error:

Traceback (most recent call last):
  File "/mnt/user/scripts/plex/main.py", line 6, in <module>
    AutoGetMovies.update()
  File "/mnt/user/scripts/plex/AutoGetMovies.py", line 18, in update
    tmdb = TMDB()
  File "/mnt/user/scripts/plex/TMDB.py", line 27, in __init__
    self.excluded_genres = self.get_genre_id_list()
  File "/mnt/user/scripts/plex/TMDB.py", line 180, in get_genre_id_list
    return genre_ids_str

It looks like genre_ids_str probably needs to be set to an empty string in this case.

**Comment by Shadow229** [comment]
fixed and removed default exclusions from the script so start point is an empty array. Left additions in as a comment for reference.

**Comment by zybron** [comment]
I didn't see a change in TMDB.py, but #6 will address it.

**Comment by Shadow229** [comment]
Weird - must not have saved. I've resaved the file and pushed. Was a tab indent causing issues the variable scope.
